services:
   server:
      build: .
      container_name: 'react-node-server'
      working_dir: /usr/app
      command: pm2-runtime /usr/app/server/index.js --watch
      ports:
         - '127.0.0.1:3000:3000'
      volumes:
         - ./app:/usr/app:ro
