version: '3.9'
services:
   db:
      image: mysql:debian
      container_name: 'db'
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: '${DB_PASS}'
         MYSQL_DATABASE: '${DB_NAME}'
      command: --default-authentication-plugin=mysql_native_password
      ports:
         - '127.0.0.1:${DB_PORT}:3306'
      volumes:
         - ./db/data:/var/lib/mysql
         - ./db/conf:/etc/mysql/conf.d:ro
   session:
      image: redis:alpine
      container_name: 'session'
      restart: always
      ports:
         - '127.0.0.1:${REDIS_PORT}:6379'
      command: redis-server --requirepass "${REDIS_PASS}"
      volumes:
         - ./session/data:/data
   server:
      build: .
      container_name: 'node'
      working_dir: /usr/app
      links:
         - db # MySQL service name
         - session # Redis service name
      depends_on:
         - db # MySQL service name
         - session # Redis service name
      restart: always
      environment:
         NODE_ENV: 'production'
         DB_HOST: 'db' # MySQL service name
         REDIS_HOST: 'session' # Redis service name
      command: pm2-runtime /usr/app/dist/backend/server/index.js --watch
      ports:
         - '127.0.0.1:${DOCKER_PORT}:${PORT}'
      volumes:
         - ./app:/usr/app:ro
         - ./logs:/usr/logs
